aragon/network-dashboard

now.json, package.json, scripts/build.sh, src/environment.js, src/index.js, src/lib/web3-utils.js, src/sentry.js, yarn.lock
Looked at supporting dynamic updates to the `environment` event prop for future runtime config but it wasn't super straightforward nor totally necessary at this exact moment.
=> Scaffold: 2 – Add sentry and simple provider utils

package.json, src/App.js, src/Routes.js, src/components/Agreement/Agreement.js, src/components/Header/Header.js, src/components/MainView.js, src/components/Proposals/ProposalDetail.js, src/components/Proposals/Proposals.js, src/index.js, src/theme.js, yarn.lock
Define the most basic set of initial routes we need. Error and route boundaries to come later.
=> Scaffold: Add super simple routes

src/components/Proposals/Proposals.js, src/hooks/disputable-voting-logic.js, src/index.js
Fonts were showing decode errors and not rendering in sub pages, this was because of pathing.
=> Update font paths

package.json, src/App.js, src/components/Agreement/Agreement.js, src/components/Footer.js, src/components/Header/Header.js, src/components/MainView.js, src/components/Proposals/Proposals.js, yarn.lock
@delfipolito I've updated the core layout to continue with Agreement, I think using a `<Layout/>` per view rather than wrapping the whole `MainView` is going to be more flexible when we work on things that require full width such as hero elements for Proposals view.
=> Add simple layout scaffold

src/components/Proposals/DisputableActionStatus.js, src/components/Proposals/FeedbackModule.js, src/components/Proposals/InfoBoxes.js, src/components/Proposals/ProposalDetail.js, src/components/Proposals/SummaryBar.js, src/hooks/disputable-voting-logic.js
=> Proposal detail: Backgrounds based on status

now.json, package.json, src/configuration/networks.js, src/environment.js, src/hooks/useAgreementDetails.js, src/hooks/useDisputableVotes.js, yarn.lock
@delfipolito This change should hopefully bring an end to local linking and branch management on connectors :)
Edit: Remember to unlink any existing syms, it's probably best to nuke `node_modules` as well
=> Environment: Upgrade to latest beta connectors

src/App.js
Fixes https://github.com/aragon/network-dashboard/issues/27
=> Routing: Use HashRouter

src/components/Agreement/Agreement.js, src/components/Agreement/AgreementBindingActions.js, src/components/Agreement/mock-data.js, src/hooks/useAgreementDetails.js
Extends `disputableApps` to display complete Binding Action details via connector.
=> Agreement: Extend disputableApps with collateral requirements

src/components/Proposals/InfoBoxes.js, src/components/Proposals/ProposalCard.js, src/configuration/networks.js, src/hooks/useDisputableVotes.js
This PR depends on:
- https://github.com/aragon/connect/pull/245
- https://github.com/aragon/connect/pull/246
=> Network: Update to latest Rinkeby deploy

src/components/AppLoader/AppLoader.js, src/components/AppLoader/AppLoaderMark.js, src/components/Header/Header.js, src/components/MainView.js
=> Improve app loader

src/components/Proposals/DisputableActionStatus.js, src/components/Proposals/DisputableActions.js, src/components/Proposals/ProposalCard.js, src/components/Proposals/ProposalDetail.js
- Move detail fields to InfoFields
- Move action collateral to details page
- Disable action buttons
- Fix card description overflow
=> General improvements

src/components/Proposals/Description.js, src/components/Proposals/ProposalCard.js, src/components/Proposals/ProposalDetails/ProposalDetails.js, src/hooks/useDisputableVotes.js
=> Decode script to get description

src/components/Proposals/ProposalDetails/DisputableActionStatus.js, src/components/Proposals/ProposalDetails/DisputableActions.js, src/components/Proposals/ProposalDetails/InfoBoxes.js, src/components/Proposals/ProposalDetails/ProposalDetails.js
This PR moves the status label to the main panel and adjusts some vertical spacing on the right hand side to try to balance the two.
I restructured the layout code to make it a bit easier navigate. I'm not sure on the component naming so please chime in!
=> Proposal: Move status label, adjust layout

src/components/Proposals/ProposalCard.js, src/components/Proposals/ProposalDetails/ProposalDetails.js, src/hooks/useDisputableVotes.js
=> Proposal detail: Show both justification and description

src/components/Layout.js, src/components/MainView.js, src/components/Proposals/DisputableStatusLabel.js, src/components/Proposals/ProposalCard.js, src/components/Proposals/ProposalDetails/ProposalDetails.js, src/index.js, src/style/breakpoints.js, src/style/theme.js
Small adjustments to improve our presentation.
Im going to centralise the new colours in a larger PR at some point soon.
=> Visuals: Update colours, contrast, page spacing

src/components/Proposals/ProposalDetails/DisputableActionStatus.js, src/components/Proposals/ProposalDetails/DisputablePeriod.js, src/components/Proposals/ProposalDetails/ProposalDetails.js, src/lib/date-utils.js
=> Fix periods

src/components/Agreement/Agreement.js, src/components/Agreement/AgreementHeader.js, src/components/Layout.js, src/components/Proposals/ProposalBanner.js, src/components/Proposals/Proposals.js
Small layout and design details, I've added the button to agreement for the future but disabled it.
=> Agreement: Tidy small details

src/components/Proposals/ProposalBanner.js
=> Banner: Change copy for PC

src/components/Proposals/ProposalDetails/ProposalDetails.js, src/components/Proposals/ProposalLoading.js
- Switch to the correct token id on proposal.
- Add space reservation for the loading graphic to avoid layout jumping on first visit before cache has been populated.
=> ProposalSingle: Token id, reserved space

src/components/Proposals/ProposalCard.js, src/hooks/useAgreementDetails.js, src/hooks/useDisputableVotes.js, src/lib/web3-utils.js
=> Proposal cards: App badges

src/components/Proposals/ProposalBanner.js, src/hooks/useDisputableVotes.js
- Update title
- Blog url
- Remove buttons
=> Update banner for precedence campaign

src/components/Proposals/ProposalDetails/ProposalDetails.js, src/lib/web3-utils.js
=> Ipfs link on justifications

now.json, src/configuration/networks.js
=> Update preview deployments to mainnet

src/hooks/useAgreementDetails.js, src/hooks/useDisputableVotes.js
Will build on this with better UX for handling errors in separate improvements.
=> Capture breaking errors via Sentry

src/components/Proposals/Proposals.js, src/lib/apps-utils.js, src/lib/web3-utils.js
=> System app icons

src/components/Proposals/ProposalDetails/DisputableActionStatus.js
They changed with adoption of a hash router.
=> Fix court hrefs

src/hooks/useAgreementDetails.js, src/hooks/useDisputableVotes.js, src/sentry.js
Little cleanup ahead of some error UX related work.
=> Sentry: Provide logging via utils

src/hooks/useSteps.js
Adds `useSteps` for applying stepped component patterns.
=> Hooks: Add useSteps

src/components/Proposals/Description.js, src/components/Proposals/ProposalCard.js
Badges in descriptions were stealing focus in the card list, this improves the tabbing experience.
Also fixes a nested dom warning introduced in https://github.com/aragon/network-dashboard/pull/74
=> Proposals: Fix card tabbing

package.json
=> Bundlewatch: Increase maxSize

src/components/Loading/LoadingFullscreen.js
See https://github.com/aragon/network-dashboard/pull/82
=> Loading Screen: Prefer renderprops

src/components/Account/AccountButton.js, src/components/Account/AccountModule.js, src/components/Account/AccountPopover.js, src/components/Account/ScreenConnected.js, src/components/Account/ScreenConnecting.js, src/components/Account/ScreenError.js, src/components/Account/ScreenProviders.js, src/components/Header/Header.js
Address the issue we discussed with "Unknown" wallet during connection. Couple of other minor tweaks to click targets and header spacing while I was in the area.
=> Account Module: Minor adjustment

package.json, src/components/Stepper/Step/Divider.js, src/components/Stepper/Step/Illustration.js, src/components/Stepper/Step/StatusVisual.js, src/components/Stepper/Step/Step.js, src/components/Stepper/Stepper.js, src/components/Stepper/stepper-descriptions.js, src/components/Stepper/stepper-statuses.js, src/components/Stepper/useStepperLayout.js, src/hooks/useMounted.js, yarn.lock
Most of this is based on my previous client implementation. Error and success info will be added separately.
=> Add stepper component

package.json, src/components/Proposals/Proposals.js, yarn.lock
Account for votes being empty on the front-end
=> Handle empty votes list

src/components/Agreement/Agreement.js, src/components/Agreement/AgreementDetails.js, src/hooks/useAgreementSign.js
Super simple signed Agreement feedback, no date, or link yet, it just needs to work and inform us that it was signed successfully.
=> Agreement: Add basic signed feedback

src/components/Proposals/ProposalDetails/StatusInfo.js
=> Status info for settled and disputed votes

src/components/Proposals/ProposalCard.js, src/components/Proposals/ProposalDetails/ProposalDetails.js, src/components/Proposals/TargetAppBadge.js
Put TargetAppBage in a separate component so it can be used in the voote cards and in the details screen
=> App badges in details screen

src/components/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js, src/components/ModalFlows/ModalFlowBase.js, src/components/Proposals/ProposalDetails/DisputableActionStatus.js, src/components/Proposals/ProposalDetails/DisputableActions.js, src/components/Stepper/stepper-descriptions.js
Basic happy path challenge action
=> Basic challenge action

src/components/Proposals/ProposalDetails/DisputableActionStatus.js, src/components/Proposals/ProposalDetails/StatusInfo.js
- Settlement period: end date fix
- "Drafting jury" quote if vote status is disputed, and "Rulling executed" otherwise
- Dispute status info  change on colors
=> Settlement period ending time & dispute fixes

src/components/ModalFlows/ChallengeProposalScreens/ChallengeProposalScreens.js, src/components/ModalFlows/SettleProposalScreens/SettleProposalScreens.js, src/components/ModalFlows/SignAgreementScreens/SignAgreementScreens.js, src/components/ModalFlows/VoteOnProposalScreens/VoteOnProposalScreens.js, src/hooks/useActions.js
Now that the actions have been tested and working for the happy path it was time to centralise them.
=> Actions: Use via hook

src/components/Proposals/ProposalDetails/DisputableActionStatus.js, src/components/Proposals/ProposalDetails/ProposalDetails.js
Move all proposal action flows to the details root.
=> Proposal: Centralize action flows

src/index.js
Too many issues with sticky cache and bad state updates at this point.
=> chore: Disable parcel hmr

src/current-environment.js, src/providers/Connect.js, src/providers/OrgApps.js
Moving these to environment so they can accessed and updated in a single source of truth
=> Connectors: Centralize config

src/current-environment.js, src/providers/AgreementSubscription.js, src/providers/OrgApps.js, src/providers/VotesSubscription.js
I made a bad and it was falling back to theGraph endpoint on org.
=> Environment: Fix incorrect org subgraph config

src/components/ModalFlows/RaiseDisputeScreens/RaiseDisputeScreens.js, src/components/Proposals/ProposalDetails/DisputableActionStatus.js, src/components/Proposals/ProposalDetails/DisputableActions.js, src/components/Proposals/ProposalDetails/ProposalDetails.js, src/hooks/useActions.js
Happy path for raising a dispute in the UI
=> Actions: Simple raise action

src/hooks/useAgreement.js
This hook only formats data from the subscription so doesn't need any of the async handling.
=> useAgreement: Remove async state management

src/components/Agreement/AgreementBindingActions.js, src/components/HelpTip.js, src/components/Proposals/ProposalDetails/InfoBoxes.js
Should help with consistency and re-use in various views.
=> Help tips: Centralise descriptions
